import { expect, test } from '@playwright/test'

test('wheel finishes before announcing the matching selection and ignores extra spins', async ({ page }) => {
  await page.goto('/')
  const games = page.locator('#games')
  await games.locator('summary').click()
  const spin = games.getByRole('button', { name: 'Spin the demo wheel', exact: true })
  await spin.click()
  await expect(spin).toBeDisabled()
  await expect(games.getByRole('status')).not.toContainText('Demo selection: A')
  await expect(spin).toBeEnabled()
  await expect(games.getByRole('status')).toContainText('Demo selection: A')
  await spin.click()
  await expect(spin).toBeEnabled()
  await expect(games.getByRole('status')).toContainText('Demo selection: B')
  await games.getByRole('button', { name: 'Reset preview', exact: true }).click()
  await expect(games.getByRole('status')).not.toContainText('Demo selection:')
})

test('grid keeps earlier reveals until reset, including when changing formats', async ({ page }) => {
  await page.goto('/')
  const games = page.locator('#games')
  await games.locator('summary').click()
  await games.getByRole('button', { name: 'Mystery grid', exact: true }).click()
  await games.getByRole('button', { name: 'Reveal square 4', exact: true }).click()
  await games.getByRole('button', { name: 'Reveal square 7', exact: true }).click()
  await expect(games.locator('.demo-mystery-grid button:disabled')).toHaveCount(2)
  await games.getByRole('button', { name: 'Wheel', exact: true }).click()
  await games.getByRole('button', { name: 'Mystery grid', exact: true }).click()
  await expect(games.locator('.demo-mystery-grid button:disabled')).toHaveCount(2)
  await games.getByRole('button', { name: 'Reset preview', exact: true }).click()
  await expect(games.locator('.demo-mystery-grid button:disabled')).toHaveCount(0)
})

test('bracket resolves both semifinals before the final and stops at the champion', async ({ page }) => {
  await page.goto('/')
  const games = page.locator('#games')
  await games.locator('summary').click()
  await games.getByRole('button', { name: 'Bracket battles', exact: true }).click()
  const play = games.locator('.demo-action')
  await expect(games.locator('.bracket-final')).toHaveText('?')
  await play.click()
  await expect(games.locator('.bracket-semifinal')).toHaveText('A?')
  await expect(games.locator('.bracket-final')).toHaveText('?')
  await play.click()
  await expect(games.locator('.bracket-semifinal')).toHaveText('AC')
  await expect(games.locator('.bracket-final')).toHaveText('?')
  await play.click()
  await expect(games.locator('.bracket-final')).toHaveText('A')
  await expect(play).toBeDisabled()
  await expect(games.locator('.demo-die')).toHaveText(['6', '3'])
  await games.getByRole('button', { name: 'Reset preview', exact: true }).click()
  await expect(play).toBeEnabled()
  await expect(games.locator('.bracket-semifinal')).toHaveText('??')
})

test('wheel honors reduced motion and lands each result beneath the pointer', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  const games = page.locator('#games')
  await games.locator('summary').click()
  await expect(games.locator('.demo-wheel')).toHaveCSS('transition-duration', '0s')
  await expect(games.locator('.demo-action')).toBeEnabled()
  for (const [index, entry] of ['A', 'B', 'C', 'D'].entries()) {
    await games.locator('.demo-action').click()
    await expect(games.getByRole('status')).toContainText(`Demo selection: ${entry}`)
    const wheel = await games.locator('.demo-wheel-wrap').boundingBox()
    const label = await games.locator(`.wheel-entry-${index}`).boundingBox()
    expect(Math.abs(label.x + label.width / 2 - wheel.x - wheel.width / 2)).toBeLessThan(2)
    expect(label.y + label.height / 2).toBeLessThan(wheel.y + wheel.height / 2)
  }
})

test('all game modes fit a narrow French screen after interaction', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 900 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/fr/')
  const games = page.locator('#games')
  await games.locator('summary').click()
  for (const name of ['Roue', 'Grille mystère', 'Tournoi']) {
    await games.getByRole('button', { name, exact: true }).click()
    if (name === 'Grille mystère') await games.getByRole('button', { name: 'Révéler la case 4', exact: true }).click()
    else await games.locator('.demo-action').click()
    const width = await page.evaluate(() => ({ actual: document.documentElement.scrollWidth, available: document.documentElement.clientWidth }))
    expect(width.actual).toBeLessThanOrEqual(width.available)
    const stage = await games.locator('.game-stage').boundingBox()
    const surface = await games.locator('.game-stage > div').boundingBox()
    expect(surface.x).toBeGreaterThanOrEqual(stage.x)
    expect(surface.x + surface.width).toBeLessThanOrEqual(stage.x + stage.width + 1)
  }
})
