import { guideContent } from './guide-content.js'

export const landingContent = {
  en: {
    linksTitle: 'Fee calculator and seller guides',
    linksIntro: 'Calculate a sale or read how fees and inventory costs affect your profit.',
    advanced: 'Advanced settings: fees, shipping and taxes',
    targetHelp: 'Percentage of your total cost. For example, 20% of $60 = $12 profit after fees.',
    back: 'WhatFees home', cta: 'Open WhatFees', calculatorTitle: 'Calculate your selling price',
    calculatorNote: 'Enter your cost and target profit to find the selling price you need after fees. Amounts are shown in CAD.',
    rounding: 'Rounded up to the next cent to meet your target.',
    feeDefaults: 'Illustrative defaults: 8% commission, 2.9% processing and $0.30 per order. Adjust these to your own rates.',
    fieldHelp: {
      cost: 'Include your purchase cost, packaging and any shipping you pay.',
      commission: 'Percentage charged on the item selling price.',
      processing: 'Percentage charged on the item price plus buyer-paid shipping and tax.',
      fixed: 'Charged once for this sale, regardless of its price.',
      shipping: 'Amount paid by the buyer. Increases processing fees; does not add to your item revenue.',
      buyerTax: 'Tax paid by the buyer. Used only to calculate payment-processing fees.',
      feeTax: 'Tax applied to commission, processing and fixed fees.',
    },
    assumptions: 'Commission applies to the item price; processing applies to the item price plus buyer-paid shipping and tax. Cost should include your item cost, packaging and any shipping you cover. This estimate excludes refunds, discounts not entered in the sale price, and other charges.',
    policy: 'Check your rate in Whatnot Seller Hub and the official fee policy.',
    invalid: 'Enter non-negative amounts and combined fee rates below 100%.',
    fields: { cost:'Your total cost', commission:'Commission rate (%)', processing:'Processing rate (%)', fixed:'Fixed fee per order', shipping:'Buyer-paid shipping', buyerTax:'Buyer-paid tax', feeTax:'Tax on fees (%)', target:'Target profit (%)' },
    results: { fees:'Estimated fees at this price', profit:'Estimated profit at this price', breakEven:'Price with no profit', target:'Required selling price' },
    pages: {
      ...guideContent.en,
      fees: {
        title: 'Whatnot Fee Calculator — Estimate Your Sale Profit | WhatFees',
        description: 'Try a Whatnot fee calculator with editable commission, processing and shipping assumptions. See estimated profit and your break-even selling price.',
        heading: 'Whatnot fee calculator',
        intro: 'Enter what your card, pack or box costs and the profit you want. Calculate the selling price needed to cover your costs and fees.',
        sections: [
          { title:'What goes into a fee estimate?', body:'Start with your total cost and target profit percentage. The calculator finds the selling price needed to cover both after fees. Advanced settings let you adjust commission, payment processing, the fixed fee, buyer-paid shipping and taxes.' },
          { title:'A $100 box is not $100 in your pocket', body:'Using the example defaults, with no shipping, tax or other charges, a $100 sale has $11.20 in estimated fees. If your total cost is $60, the estimated profit is $28.80. Change the inputs to reflect your own category, market and costs; these are example assumptions, not a guaranteed Whatnot rate.' },
          { title:'Why your category and sales tier matter', body:'Use the commission rate shown in your own Seller Hub. Category, market, sales tier and promotions can change the rate. Payment processing still needs its own input. Check your final order breakdown after a sale rather than treating an estimate as a settlement.' },
          { title:'Break-even and target-profit prices', body:'With a $60 total cost, the example rates of 8% commission and 2.9% processing plus $0.30 per order give a break-even price of $67.68. A 20% profit target means $12 after fees and a required price of $81.15. These examples exclude shipping and taxes; the calculator rounds required prices up to the next cent.' },
          { title:'Use your inventory costs in the app', body:'Record costs for lots or individual items in WhatFees and calculate a break-even price. Pro adds target-profit pricing, sales tracking and portfolio reports. This public calculator works without an account; the full app requires Google sign-in.' },
        ],
      },
      inventory: {
        title: 'TCG Inventory Tracker for Cards, Boxes & Packs | WhatFees',
        description: 'Organize TCG lots and individual cards, keep purchase costs close to pricing, and review sales and profit with WhatFees on web and Android.',
        heading: 'TCG inventory tracking for cards, boxes and packs',
        intro: 'A sealed box, its loose packs and the cards inside are different things to sell. Keep your purchase costs and selling decisions connected as your inventory changes.',
        sections: [
          { title:'Choose grouped inventory or individual items', body:'Use a lot for inventory bought together, such as a case, a group of boxes or a mixed stack. Use individual items when each card or collectible has its own name and cost. WhatFees supports both starting points so you can organize the purchase in a way that matches how you sell it.' },
          { title:'Keep costs with the inventory', body:'Record what you paid and the quantities relevant to your setup. A price is easier to judge when you can see its cost basis and fee assumptions alongside it. Avoid treating every dollar of sales as recovered profit while part of the original investment remains tied up in unsold inventory.' },
          { title:'Prepare for a show, then review the outcome', body:'Prepare individual or bundle pricing in the live workflow. With Pro, record sales and review estimated profit, investment recovery and portfolio reports. Whatnot import workflows bring marketplace sales into view; Shopify product linking helps associate store products with your lots. These are specific workflows, not a promise of universal marketplace sync.' },
          { title:'Access on web and Android', body:'Open WhatFees in a browser or use the Android app with Google sign-in. Inventory setup and basic pricing are free. Pro costs US$10 once and adds target-profit pricing, sales tracking, portfolio reports and expert mode. Use the same Google account to access your purchase on both platforms.' },
        ],
      },
    },
  },
  fr: {
    linksTitle: 'Calculateur de frais et guides de vente',
    linksIntro: 'Calculez une vente ou consultez les guides sur les frais et les coûts d’inventaire.',
    advanced: 'Paramètres avancés : frais, livraison et taxes',
    targetHelp: 'Pourcentage de votre coût total. Par exemple, 20 % sur 60 $ = 12 $ de profit après frais.',
    back: 'Accueil WhatFees', cta: 'Ouvrir WhatFees', calculatorTitle: 'Calculez votre prix de vente',
    calculatorNote: 'Entrez votre coût et votre profit cible pour trouver le prix de vente requis après frais. Les montants sont affichés en CAD.',
    rounding: 'Arrondi au cent supérieur pour atteindre votre cible.',
    feeDefaults: 'Valeurs indicatives : commission de 8 %, traitement de 2,9 % et frais fixes de 0,30 $ par commande. Adaptez-les à vos propres taux.',
    fieldHelp: {
      cost: 'Incluez le coût d’achat, l’emballage et la livraison que vous payez.',
      commission: 'Pourcentage prélevé sur le prix de vente de l’article.',
      processing: 'Pourcentage prélevé sur le prix de l’article, la livraison et les taxes payées par l’acheteur.',
      fixed: 'Prélevés une fois pour cette vente, quel que soit son prix.',
      shipping: 'Montant payé par l’acheteur. Augmente les frais de traitement sans ajouter de revenu à votre article.',
      buyerTax: 'Taxes payées par l’acheteur. Servent uniquement à calculer les frais de traitement.',
      feeTax: 'Taxes appliquées à la commission, au traitement et aux frais fixes.',
    },
    assumptions: 'La commission porte sur le prix de l’article; le traitement porte sur ce prix plus la livraison et les taxes payées par l’acheteur. Le coût doit inclure l’article, l’emballage et la livraison que vous payez. Les remboursements, les rabais non inclus dans le prix et les autres frais ne sont pas calculés.',
    policy: 'Vérifiez votre taux dans Seller Hub et la politique officielle de frais Whatnot.',
    invalid: 'Entrez des montants positifs ou nuls et des taux de frais combinés inférieurs à 100 %.',
    fields: { cost:'Votre coût total', commission:'Commission (%)', processing:'Traitement (%)', fixed:'Frais fixes par commande', shipping:'Livraison payée par l’acheteur', buyerTax:'Taxes payées par l’acheteur', feeTax:'Taxes sur les frais (%)', target:'Profit cible (%)' },
    results: { fees:'Frais estimés à ce prix', profit:'Profit estimé à ce prix', breakEven:'Prix sans profit', target:'Prix de vente requis' },
    pages: {
      ...guideContent.fr,
      fees: {
        title: 'Calculateur de frais Whatnot et de profits | WhatFees',
        description: 'Essayez un calculateur de frais Whatnot avec taux de commission, traitement et livraison ajustables. Consultez votre profit et votre seuil de rentabilité.',
        heading: 'Calculateur de frais Whatnot',
        intro: 'Entrez le coût de votre carte, paquet ou boîte et le profit souhaité. Calculez le prix de vente requis pour couvrir vos coûts et les frais.',
        sections: [
          { title:'Que comprend une estimation de frais ?', body:'Commencez par votre coût total et votre pourcentage de profit cible. Le calculateur trouve le prix de vente requis pour couvrir les deux après frais. Les paramètres avancés permettent d’ajuster la commission, le traitement, les frais fixes, la livraison payée par l’acheteur et les taxes.' },
          { title:'Une boîte à 100 $ ne laisse pas 100 $', body:'Avec les valeurs indicatives, sans livraison, taxes ni autres frais, une vente de 100 $ entraîne des frais estimés de 11,20 $. Pour un coût total de 60 $, le profit estimé est de 28,80 $. Adaptez les champs à votre catégorie, votre marché et vos coûts : les valeurs de départ ne garantissent aucun taux Whatnot.' },
          { title:'La catégorie et le palier de ventes comptent', body:'Utilisez le taux de commission affiché dans votre Seller Hub. La catégorie, le marché, le palier de ventes et les promotions peuvent le modifier. Le traitement des paiements reste un champ distinct. Vérifiez le détail de la commande après la vente pour connaître les retenues finales.' },
          { title:'Seuil de rentabilité et profit cible', body:'Pour un coût total de 60 $, les taux indicatifs de 8 % de commission et 2,9 % de traitement plus 0,30 $ par commande donnent un seuil de rentabilité de 67,68 $. Une cible de 20 % représente 12 $ après frais et un prix requis de 81,15 $. Ces exemples excluent la livraison et les taxes; le calculateur arrondit les prix requis au cent supérieur.' },
          { title:'Utilisez vos coûts d’inventaire dans l’application', body:'Notez les coûts de vos lots ou articles dans WhatFees et calculez le seuil de rentabilité. Pro ajoute le profit cible, le suivi des ventes et les rapports de portefeuille. Ce calculateur public fonctionne sans compte; l’application complète exige une connexion Google.' },
        ],
      },
      inventory: {
        title: 'Suivi d’inventaire TCG : cartes, boîtes et paquets | WhatFees',
        description: 'Organisez vos lots TCG et cartes individuelles, gardez les coûts près des prix et consultez ventes et profits avec WhatFees sur le Web et Android.',
        heading: 'Suivi d’inventaire TCG : cartes, boîtes et paquets',
        intro: 'Une boîte scellée, ses paquets et les cartes qu’elle contient sont des articles différents à vendre. Gardez vos coûts et vos décisions de vente liés au fil des changements.',
        sections: [
          { title:'Inventaire groupé ou articles individuels', body:'Utilisez un lot pour un achat groupé : caisse, ensemble de boîtes ou pile de cartes. Choisissez les articles individuels lorsque chaque carte ou objet possède son nom et son coût. WhatFees permet ces deux points de départ pour correspondre à votre façon de vendre.' },
          { title:'Gardez les coûts avec l’inventaire', body:'Notez ce que vous avez payé et les quantités de votre configuration. Un prix se juge mieux lorsque son coût et les hypothèses de frais sont accessibles. Les revenus de vente ne constituent pas tous un profit récupéré si une partie de l’investissement reste dans l’inventaire non vendu.' },
          { title:'Préparez le direct, puis consultez les résultats', body:'Préparez les prix individuels ou en ensemble dans la vue En direct. Avec Pro, enregistrez les ventes et consultez profits estimés, récupération de l’investissement et rapports de portefeuille. Les importations Whatnot et la liaison de produits Shopify sont des flux précis, sans promesse de synchronisation universelle.' },
          { title:'Sur le Web et Android', body:'Ouvrez WhatFees dans un navigateur ou utilisez l’application Android avec une connexion Google. L’inventaire et les prix de base sont gratuits. Pro coûte 10 $ US en achat unique et ajoute le profit cible, les ventes, les rapports de portefeuille et le mode expert. Utilisez le même compte Google pour accéder à votre achat sur les deux plateformes.' },
        ],
      },
    },
  },
}
