export const landingContent = {
  en: {
    linksTitle: 'Tools for your next selling decision',
    linksIntro: 'Try a calculation here, then bring your inventory and sales together in the app.',
    back: 'WhatFees home', cta: 'Open the seller toolkit', calculatorTitle: 'Try your numbers',
    calculatorNote: 'Illustrative defaults: 8% commission, 2.9% processing and $0.30 fixed fee. Enter your own rates. Use one currency throughout; amounts are shown in CAD.',
    assumptions: 'Commission applies to the item price; processing applies to the item price plus buyer-paid shipping and tax. Cost should include your item cost, packaging and any shipping you cover. This estimate excludes refunds, discounts not entered in the sale price, and other charges.',
    policy: 'Check your rate in Whatnot Seller Hub and the official fee policy.',
    invalid: 'Enter non-negative amounts and combined fee rates below 100%.',
    fields: { sale:'Item sale price', cost:'Your total cost', commission:'Commission rate (%)', processing:'Processing rate (%)', fixed:'Fixed fee per order', shipping:'Buyer-paid shipping', buyerTax:'Buyer-paid tax', feeTax:'Tax on fees (%)', target:'Target profit' },
    results: { fees:'Estimated fees', profit:'Estimated profit', breakEven:'Break-even price', target:'Price for your target profit' },
    pages: {
      fees: {
        title: 'Whatnot Fee Calculator — Estimate Your Sale Profit | WhatFees',
        description: 'Try a Whatnot fee calculator with editable commission, processing and shipping assumptions. See estimated profit and your break-even selling price.',
        heading: 'Whatnot fee calculator',
        intro: 'A winning bid is your revenue, not your profit. Estimate the fees on a card, pack or box before deciding what you can afford to accept.',
        sections: [
          { title:'What goes into a fee estimate?', body:'Start with the item selling price. Commission and payment processing can use different bases, so a single percentage on the item price can miss part of the deduction. The calculator separates commission, processing, buyer-paid shipping and buyer-paid tax. Add tax on fees if it applies to your sale.' },
          { title:'A $100 box is not $100 in your pocket', body:'Using the example defaults, with no shipping, tax or other charges, a $100 sale has $11.20 in estimated fees. If your total cost is $60, the estimated profit is $28.80. Change the inputs to reflect your own category, market and costs; these are example assumptions, not a guaranteed Whatnot rate.' },
          { title:'Why your category and sales tier matter', body:'Use the commission rate shown in your own Seller Hub. Category, market, sales tier and promotions can change the rate. Payment processing still needs its own input. Check your final order breakdown after a sale rather than treating an estimate as a settlement.' },
          { title:'Take the calculation into your selling workflow', body:'WhatFees keeps inventory costs close to your pricing decisions. Set up lots or individual items, estimate break-even prices and use Pro for target-profit calculations, sales tracking and portfolio reports. You can use the public calculator here without signing in; the full app requires Google sign-in.' },
        ],
      },
      breakEven: {
        title: 'Break-Even Calculator for Whatnot Sellers | WhatFees',
        description: 'Find a selling price that covers inventory costs and fees. Try an editable break-even calculator, then add a target profit for your cards and boxes.',
        heading: 'Break-even calculator for sellers',
        intro: 'Before accepting an offer or choosing a starting price, know the amount needed to recover your cost after selling fees.',
        sections: [
          { title:'Break-even starts with your real cost', body:'Include what you paid for the item and other costs you cover, such as packaging or seller-paid shipping. Use consistent currency amounts. For a grouped purchase, decide what portion of the lot cost belongs to the box, pack or card you are selling before entering it here.' },
          { title:'Work backward from what you need to keep', body:'With percentage fees, simply adding the fee percentage to your cost will usually leave a shortfall. For this model, the required price is (cost + fixed fee effects + target profit) divided by (1 − effective percentage fee rate). Buyer-paid shipping and tax contribute to the processing fee, not to item-sale revenue.' },
          { title:'A practical minimum-price example', body:'With $60 in total cost, 8% commission, 2.9% processing and a $0.30 fixed fee, and no shipping or taxes, the break-even price is $67.68. The calculator rounds a required price upward to the next cent. Add a target profit to see the price needed to keep that amount under the same assumptions.' },
          { title:'Break-even is a decision aid', body:'Recovering an item’s cost is different from covering your whole business. Time, overhead, refunds and currency conversion can also affect the result. Use the calculator for a clearly defined sale, then review recorded sales and portfolio performance in WhatFees to see how your selling activity adds up.' },
        ],
      },
      inventory: {
        title: 'TCG Inventory Tracker for Cards, Boxes & Packs | WhatFees',
        description: 'Organize TCG lots and individual cards, keep purchase costs close to pricing, and review sales and profit with WhatFees on web and Android.',
        heading: 'TCG inventory tracking for cards, boxes and packs',
        intro: 'A sealed box, its loose packs and the cards inside are different things to sell. Keep your purchase costs and selling decisions connected as your inventory changes.',
        sections: [
          { title:'Choose grouped inventory or individual items', body:'Use a lot for inventory bought together, such as a case, a group of boxes or a mixed stack. Use individual items when each card or collectible has its own name and cost. WhatFees supports both starting points so you can organize the purchase in a way that matches how you sell it.' },
          { title:'Keep costs with the inventory', body:'Record what you paid and the quantities relevant to your setup. A price is easier to judge when you can see its cost basis and fee assumptions alongside it. Avoid treating every dollar of sales as recovered profit while part of the original investment remains tied up in unsold inventory.' },
          { title:'Prepare for a show, then review the outcome', body:'Prepare individual or bundle pricing in the live workflow. With Pro, record sales and review estimated profit, investment recovery and portfolio reports. Whatnot import workflows bring marketplace sales into view; Shopify product linking helps associate store products with your lots. These are specific workflows, not a promise of universal marketplace sync.' },
          { title:'One workspace across web and Android', body:'Open WhatFees in a browser or use the Android app. Google sign-in is required for the full app. Start with inventory setup and basic pricing, then check the current Pro options in the app for target-profit calculations, sales tracking, portfolio reports and expert mode.' },
        ],
      },
    },
  },
  fr: {
    linksTitle: 'Des outils pour votre prochaine vente',
    linksIntro: 'Essayez un calcul ici, puis réunissez inventaire et ventes dans l’application.',
    back: 'Accueil WhatFees', cta: 'Ouvrir les outils de vente', calculatorTitle: 'Essayez vos chiffres',
    calculatorNote: 'Valeurs indicatives : commission de 8 %, traitement de 2,9 % et frais fixes de 0,30 $. Entrez vos propres taux. Utilisez une seule devise; les montants sont affichés en CAD.',
    assumptions: 'La commission porte sur le prix de l’article; le traitement porte sur ce prix plus la livraison et les taxes payées par l’acheteur. Le coût doit inclure l’article, l’emballage et la livraison que vous payez. Les remboursements, les rabais non inclus dans le prix et les autres frais ne sont pas calculés.',
    policy: 'Vérifiez votre taux dans Seller Hub et la politique officielle de frais Whatnot.',
    invalid: 'Entrez des montants positifs ou nuls et des taux de frais combinés inférieurs à 100 %.',
    fields: { sale:'Prix de vente de l’article', cost:'Votre coût total', commission:'Commission (%)', processing:'Traitement (%)', fixed:'Frais fixes par commande', shipping:'Livraison payée par l’acheteur', buyerTax:'Taxes payées par l’acheteur', feeTax:'Taxes sur les frais (%)', target:'Profit cible' },
    results: { fees:'Frais estimés', profit:'Profit estimé', breakEven:'Prix au seuil de rentabilité', target:'Prix pour votre profit cible' },
    pages: {
      fees: {
        title: 'Calculateur de frais Whatnot et de profits | WhatFees',
        description: 'Essayez un calculateur de frais Whatnot avec taux de commission, traitement et livraison ajustables. Consultez votre profit et votre seuil de rentabilité.',
        heading: 'Calculateur de frais Whatnot',
        intro: 'Une enchère gagnante est un revenu, pas un profit. Estimez les frais d’une carte, d’un paquet ou d’une boîte avant de décider du prix à accepter.',
        sections: [
          { title:'Que comprend une estimation de frais ?', body:'Commencez par le prix de vente de l’article. La commission et le traitement des paiements peuvent porter sur des montants différents. Le calculateur sépare ces taux, la livraison et les taxes payées par l’acheteur. Ajoutez un taux de taxes sur les frais lorsqu’il s’applique à votre vente.' },
          { title:'Une boîte à 100 $ ne laisse pas 100 $', body:'Avec les valeurs indicatives, sans livraison, taxes ni autres frais, une vente de 100 $ entraîne des frais estimés de 11,20 $. Pour un coût total de 60 $, le profit estimé est de 28,80 $. Adaptez les champs à votre catégorie, votre marché et vos coûts : les valeurs de départ ne garantissent aucun taux Whatnot.' },
          { title:'La catégorie et le palier de ventes comptent', body:'Utilisez le taux de commission affiché dans votre Seller Hub. La catégorie, le marché, le palier de ventes et les promotions peuvent le modifier. Le traitement des paiements reste un champ distinct. Vérifiez le détail de la commande après la vente pour connaître les retenues finales.' },
          { title:'Du calcul à votre activité de vente', body:'WhatFees garde les coûts près de vos décisions de prix. Configurez des lots ou des articles, estimez le seuil de rentabilité et utilisez Pro pour le profit cible, le suivi des ventes et les rapports de portefeuille. Ce calculateur public fonctionne sans connexion; l’application complète exige une connexion Google.' },
        ],
      },
      breakEven: {
        title: 'Calculateur de seuil de rentabilité pour vendeurs | WhatFees',
        description: 'Trouvez un prix qui couvre vos coûts et frais de vente. Essayez le calculateur de seuil de rentabilité et ajoutez un profit cible pour vos cartes et boîtes.',
        heading: 'Calculateur de seuil de rentabilité pour vendeurs',
        intro: 'Avant d’accepter une offre ou de choisir un prix de départ, trouvez le montant nécessaire pour récupérer votre coût après les frais de vente.',
        sections: [
          { title:'Commencez par votre coût réel', body:'Incluez le coût de l’article et les dépenses que vous assumez, comme l’emballage ou la livraison. Gardez la même devise pour tous les montants. Pour un achat groupé, déterminez la part du coût du lot attribuée à la boîte, au paquet ou à la carte vendue.' },
          { title:'Partez du montant à conserver', body:'Ajouter simplement le pourcentage de frais au coût laisse souvent un manque. Dans ce modèle, le prix requis est (coût + effets des frais fixes + profit cible) divisé par (1 − taux effectif des frais proportionnels). La livraison et les taxes payées par l’acheteur augmentent les frais de traitement, sans devenir un revenu de vente de l’article.' },
          { title:'Un exemple de prix minimum', body:'Avec un coût total de 60 $, une commission de 8 %, un traitement de 2,9 % et des frais fixes de 0,30 $, sans livraison ni taxes, le seuil de rentabilité est de 67,68 $. Le calculateur arrondit le prix requis au cent supérieur. Ajoutez un profit cible pour trouver le prix nécessaire selon les mêmes hypothèses.' },
          { title:'Un outil pour décider', body:'Récupérer le coût d’un article ne couvre pas forcément toute votre activité. Le temps, les frais généraux, les remboursements et les conversions de devises peuvent aussi compter. Calculez une vente précise, puis consultez les ventes enregistrées et le portefeuille dans WhatFees pour comprendre les résultats d’ensemble.' },
        ],
      },
      inventory: {
        title: 'Suivi d’inventaire TCG : cartes, boîtes et paquets | WhatFees',
        description: 'Organisez vos lots TCG et cartes individuelles, gardez les coûts près des prix et consultez ventes et profits avec WhatFees sur le Web et Android.',
        heading: 'Suivi d’inventaire TCG : cartes, boîtes et paquets',
        intro: 'Une boîte scellée, ses paquets et les cartes qu’elle contient sont des articles différents à vendre. Gardez vos coûts et vos décisions de vente liés au fil des changements.',
        sections: [
          { title:'Inventaire groupé ou articles individuels', body:'Utilisez un lot pour un achat groupé : caisse, ensemble de boîtes ou pile de cartes. Choisissez les articles individuels lorsque chaque carte ou objet possède son nom et son coût. WhatFees permet ces deux points de départ pour correspondre à votre façon de vendre.' },
          { title:'Gardez les coûts avec l’inventaire', body:'Notez ce que vous avez payé et les quantités de votre configuration. Un prix se juge mieux lorsque son coût et les hypothèses de frais sont accessibles. Les revenus de vente ne constituent pas tous un profit récupéré si une partie de l’investissement reste dans l’inventaire non vendu.' },
          { title:'Préparez le direct, puis consultez les résultats', body:'Préparez les prix individuels ou en ensemble dans la vue En direct. Avec Pro, enregistrez les ventes et consultez profits estimés, récupération de l’investissement et rapports de portefeuille. Les importations Whatnot et la liaison de produits Shopify sont des flux précis, sans promesse de synchronisation universelle.' },
          { title:'Sur le Web et Android', body:'Ouvrez WhatFees dans un navigateur ou utilisez l’application Android. Une connexion Google est nécessaire. Commencez avec l’inventaire et les prix de base, puis consultez les options Pro actuelles dans l’application pour le profit cible, les ventes, les rapports et le mode expert.' },
        ],
      },
    },
  },
}
