export const productContent = {
  en: {
    proofKicker: 'INVENTORY · PRICING · SALES',
    proofTitle: 'Price a lot. Record a sale. Review the result.',
    proofIntro: 'Follow a lot from pricing to sales with these interactive illustrations. All figures are examples.',
    scenarios: [
      { title: 'Building a bundle?', moment: 'BEFORE THE SHOW', body: 'Select items from your inventory and prepare to price them individually or as a bundle.', kind: 'live', caption: 'Live · choose individual or bundle pricing' },
      { title: 'Just closed a sale?', moment: 'AFTER THE SALE', body: 'Review your sale history, estimated profit and how much of your original investment you have recovered.', kind: 'sales', caption: 'Sales · review what sold and what remains' },
      { title: 'Planning your next buy?', moment: 'BETWEEN SHOWS', body: 'See how net sales recover a lot’s original investment across shows. This chart uses fictional data.', kind: 'chart', caption: 'Portfolio example · investment recovery' },
    ],
    gamesKicker: 'GAMES AND SPECTATOR SHARING',
    gamesTitle: 'Run the game. Share the spectator link.',
    gamesIntro: 'Run a wheel, mystery grid or bracket battle, then share a spectator page so your audience can follow along.',
    previewLabel: 'INTERACTIVE ILLUSTRATION',
    previewNote: 'Local illustration. Both panels use the same demo state; the app shares a separate spectator page.',
    hostLabel: 'HOST CONTROLS', spectatorLabel: 'SPECTATOR VIEW',
    spectatorWaiting: 'Waiting for the host.', spectatorGrid: 'Revealed squares',
    games: [
      { id: 'wheel', name: 'Wheel', body: 'Spin the wheel from your controls. Spectators see the spin and result.' },
      { id: 'grid', name: 'Mystery grid', body: 'Choose a square to reveal. The shared page shows which squares have been revealed.' },
      { id: 'bracket', name: 'Bracket battles', body: 'Roll the dice for each matchup. Spectators follow the results and the remaining bracket.' },
    ],
    previewPrompt: 'Try a format below.',
    spin: 'Spin the demo wheel',
    spinResult: 'Demo selection:',
    spinning: 'Spinning…',
    reveal: 'Reveal square',
    revealed: 'Square {n} revealed',
    gridPrompt: 'Pick a square to try a reveal.',
    bracketAction: 'Roll the next matchup',
    bracketPrompt: 'Roll the two semifinals, then the final.',
    matchResult: 'Match {n}: {winner} advances',
    duelLabel: 'Example head-to-head dice roll',
    dieResult: 'Example die result',
    bracketResult: 'Demo winner:',
    reset: 'Reset preview',
    bracketLabel: 'Illustrative four-entry bracket',
    shareTitle: 'One link for the audience.',
    shareSteps: [
      { title: 'Start a session', body: 'Open spectator sharing from your game.' },
      { title: 'Share the view', body: 'Copy the spectator URL or show its QR code.' },
      { title: 'Keep the controls', body: 'Spectators only watch. You run the game and end the session.' },
    ],
    plansKicker: 'PRICING',
    plansTitle: 'Free or Pro. No subscription.',
    freePrice: '$0', freeBilling: 'No purchase required',
    proPrice: 'US$10', proBilling: 'One-time purchase',
    free: 'Free', freeIntro: 'For setting up your inventory and working through basic pricing.',
    freeItems: ['Inventory setup', 'Basic pricing tools'],
    pro: 'Pro', proIntro: 'For target-profit pricing, sales tracking and portfolio reports.',
    proItems: ['Target-profit price calculator', 'Sales tracking', 'Portfolio reports', 'Expert mode'],
    pricingNote: 'Buy Pro once on web or Android. Use the same Google account to access Pro on both.',
    signIn: 'Google sign-in is required to use the app.',
    plansCta: 'Open WhatFees',
  },
  fr: {
    proofKicker: 'INVENTAIRE · PRIX · VENTES',
    proofTitle: 'Fixer un prix. Enregistrer une vente. Voir le résultat.',
    proofIntro: 'Suivez un lot, du prix aux ventes, avec ces illustrations interactives. Tous les montants sont fictifs.',
    scenarios: [
      { title: 'Vous préparez un ensemble ?', moment: 'AVANT LE DIRECT', body: 'Sélectionnez des articles de votre inventaire pour préparer leur prix individuel ou en ensemble.', kind: 'live', caption: 'En direct · prix individuel ou en ensemble' },
      { title: 'Vous venez de vendre ?', moment: 'APRÈS LA VENTE', body: 'Consultez l’historique, le profit estimé et la part de votre investissement initial déjà récupérée.', kind: 'sales', caption: 'Ventes · ce qui est vendu et ce qu’il reste' },
      { title: 'Vous prévoyez un achat ?', moment: 'ENTRE LES DIRECTS', body: 'Voyez comment les ventes nettes récupèrent l’investissement initial d’un lot au fil des directs. Ce graphique utilise des données fictives.', kind: 'chart', caption: 'Exemple de portefeuille · récupération de l’investissement' },
    ],
    gamesKicker: 'JEUX ET PARTAGE SPECTATEUR',
    gamesTitle: 'Animez le jeu. Partagez le lien spectateur.',
    gamesIntro: 'Lancez une roue, une grille mystère ou un tournoi, puis partagez une page spectateur pour que votre public suive le jeu.',
    previewLabel: 'ILLUSTRATION INTERACTIVE',
    previewNote: 'Illustration locale. Les deux panneaux utilisent les mêmes données démo; l’application partage une page spectateur distincte.',
    hostLabel: 'COMMANDES DU VENDEUR', spectatorLabel: 'VUE SPECTATEUR',
    spectatorWaiting: 'En attente du vendeur.', spectatorGrid: 'Cases révélées',
    games: [
      { id: 'wheel', name: 'Roue', body: 'Lancez la roue avec vos commandes. Les spectateurs voient le mouvement et le résultat.' },
      { id: 'grid', name: 'Grille mystère', body: 'Choisissez une case à révéler. La page partagée montre les cases révélées.' },
      { id: 'bracket', name: 'Tournoi', body: 'Lancez les dés pour chaque duel. Les spectateurs suivent les résultats et les participants restants.' },
    ],
    previewPrompt: 'Essayez un format ci-dessous.',
    spin: 'Faire tourner la roue démo',
    spinResult: 'Sélection démo :',
    spinning: 'La roue tourne…',
    reveal: 'Révéler la case',
    revealed: 'Case {n} révélée',
    gridPrompt: 'Choisissez une case à révéler.',
    bracketAction: 'Lancer le prochain duel',
    bracketPrompt: 'Jouez les deux demi-finales, puis la finale.',
    matchResult: 'Duel {n} : {winner} avance',
    duelLabel: 'Exemple de duel aux dés',
    dieResult: 'Résultat du dé de démonstration',
    bracketResult: 'Gagnant démo :',
    reset: 'Réinitialiser l’aperçu',
    bracketLabel: 'Illustration d’un tournoi à quatre participants',
    shareTitle: 'Un lien pour le public.',
    shareSteps: [
      { title: 'Lancez une session', body: 'Ouvrez le partage spectateur depuis votre jeu.' },
      { title: 'Partagez la vue', body: 'Copiez le lien spectateur ou affichez son code QR.' },
      { title: 'Gardez les commandes', body: 'Le public regarde seulement. Vous gérez le jeu et terminez la session.' },
    ],
    plansKicker: 'PRIX',
    plansTitle: 'Gratuit ou Pro. Aucun abonnement.',
    freePrice: '0 $', freeBilling: 'Aucun achat requis',
    proPrice: '10 $ US', proBilling: 'Achat unique',
    free: 'Gratuit', freeIntro: 'Pour organiser votre inventaire et utiliser les outils de prix de base.',
    freeItems: ['Configuration de l’inventaire', 'Outils de tarification de base'],
    pro: 'Pro', proIntro: 'Pour calculer un prix selon votre profit cible, suivre les ventes et consulter les rapports de portefeuille.',
    proItems: ['Calcul du prix selon le profit cible', 'Suivi des ventes', 'Rapports de portefeuille', 'Mode expert'],
    pricingNote: 'Achetez Pro une fois sur le Web ou Android. Utilisez le même compte Google pour accéder à Pro sur les deux.',
    signIn: 'Une connexion Google est nécessaire pour utiliser l’application.',
    plansCta: 'Ouvrir WhatFees',
  },
}
