export const productContent = {
  en: {
    actualApp: 'ACTUAL APP · FICTIONAL DEMO DATA',
    portfolioExample: 'PORTFOLIO EXAMPLE · FICTIONAL DATA',
    openImage: 'Open full-size screenshot in a new tab',
    heroAlt: 'WhatFees Sales screen with a sales snapshot, investment recovery and sale history using fictional demo data',
    heroCaption: 'The sale is only half the story.',
    heroDetail: 'Review your sales, costs and estimated profit in one place.',
    proofKicker: 'THREE MOMENTS. ONE WORKSPACE.',
    proofTitle: 'Put it to work on your next show.',
    proofIntro: 'Explore real app screens and a portfolio chart example.',
    scenarios: [
      { title: 'Building a bundle?', moment: 'BEFORE THE SHOW', body: 'Select items from your inventory and prepare to price them individually or as a bundle.', src: 'live.webp', alt: 'WhatFees Live screen showing the individual and bundle pricing selector', caption: 'Live · choose individual or bundle pricing' },
      { title: 'Just closed a sale?', moment: 'AFTER THE SALE', body: 'Review your sale history, estimated profit and how much of your original investment you have recovered.', src: 'sales.webp', alt: 'WhatFees Sales screen showing a sales snapshot, investment recovery and sale history with fictional data', caption: 'Sales · review what sold and what remains' },
      { title: 'Planning your next buy?', moment: 'BETWEEN SHOWS', body: 'See how net sales recover a lot’s original investment across shows. This chart uses fictional data.', kind: 'chart', caption: 'Portfolio example · investment recovery' },
    ],
    gamesKicker: 'GIVE THE SHOW A MOMENT',
    gamesTitle: 'Your controls. Their front-row view.',
    gamesIntro: 'Run a wheel, mystery grid or bracket battle, then share a spectator page so your audience can follow along.',
    previewLabel: 'INTERACTIVE ILLUSTRATION',
    previewNote: 'A simplified demo of the game formats. This is not the app or a live broadcast.',
    games: [
      { id: 'wheel', name: 'Wheel', body: 'Add a spin to the show. The shared view lets spectators follow the wheel while you run it.' },
      { id: 'grid', name: 'Mystery grid', body: 'Make the reveal part of the show. You reveal a square; spectators follow the result on their shared page.' },
      { id: 'bracket', name: 'Bracket battles', body: 'Build a head-to-head moment. Roll head-to-head dice matchups while your audience follows the bracket.' },
    ],
    previewPrompt: 'Try a format below.',
    spin: 'Spin the demo wheel',
    spinResult: 'Demo selection:',
    spinning: 'Spinning…',
    reveal: 'Reveal square',
    revealed: 'Square {n} revealed',
    gridPrompt: 'Pick a square to try a reveal.',
    bracketAction: 'Roll the next matchup',
    bracketPrompt: 'Roll the two semifinals, then the final.',
    matchResult: 'Match {n}: {winner} advances',
    duelLabel: 'Example head-to-head dice roll',
    dieResult: 'Example die result',
    bracketResult: 'Demo winner:',
    reset: 'Reset preview',
    bracketLabel: 'Illustrative four-entry bracket',
    shareTitle: 'One link for the audience.',
    shareSteps: [
      { title: 'Start a session', body: 'Open spectator sharing from your game.' },
      { title: 'Share the view', body: 'Copy the spectator URL or show its QR code.' },
      { title: 'Keep the controls', body: 'Spectators only watch. You run the game and end the session.' },
    ],
    plansKicker: 'KNOW WHAT TO EXPECT',
    plansTitle: 'Start with the basics. Add Pro when it fits.',
    free: 'Free', freeIntro: 'For setting up your inventory and working through basic pricing.',
    freeItems: ['Inventory setup', 'Basic pricing tools'],
    pro: 'Pro', proIntro: 'For target-profit pricing and a deeper view of your selling activity.',
    proItems: ['Target-profit price calculator', 'Sales tracking', 'Portfolio reports', 'Expert mode'],
    pricingNote: 'Check the app for current Pro pricing and plan details.',
    signIn: 'Google sign-in is required to use the app.',
    plansCta: 'Explore plans in the app',
  },
  fr: {
    actualApp: 'VRAIE APPLICATION · DONNÉES FICTIVES',
    portfolioExample: 'EXEMPLE DE PORTEFEUILLE · DONNÉES FICTIVES',
    openImage: 'Ouvrir la capture en taille réelle dans un nouvel onglet',
    heroAlt: 'Écran Ventes de WhatFees montrant un bilan, la récupération de l’investissement et l’historique avec des données fictives',
    heroCaption: 'La vente ne raconte pas tout.',
    heroDetail: 'Retrouvez vos ventes, vos coûts et votre profit estimé au même endroit.',
    proofKicker: 'TROIS MOMENTS. UN MÊME ESPACE.',
    proofTitle: 'À vos côtés pour le prochain direct.',
    proofIntro: 'Explorez les écrans de l’application et un exemple de graphique de portefeuille.',
    scenarios: [
      { title: 'Vous préparez un ensemble ?', moment: 'AVANT LE DIRECT', body: 'Sélectionnez des articles de votre inventaire pour préparer leur prix individuel ou en ensemble.', src: 'live.webp', alt: 'Écran En direct de WhatFees avec le sélecteur de tarification individuelle ou en ensemble', caption: 'En direct · prix individuel ou en ensemble' },
      { title: 'Vous venez de vendre ?', moment: 'APRÈS LA VENTE', body: 'Consultez l’historique, le profit estimé et la part de votre investissement initial déjà récupérée.', src: 'sales.webp', alt: 'Écran Ventes de WhatFees avec bilan, récupération de l’investissement et historique avec des données fictives', caption: 'Ventes · ce qui est vendu et ce qu’il reste' },
      { title: 'Vous prévoyez un achat ?', moment: 'ENTRE LES DIRECTS', body: 'Voyez comment les ventes nettes récupèrent l’investissement initial d’un lot au fil des directs. Ce graphique utilise des données fictives.', kind: 'chart', caption: 'Exemple de portefeuille · récupération de l’investissement' },
    ],
    gamesKicker: 'UN MOMENT À PARTAGER EN DIRECT',
    gamesTitle: 'Vous animez. Le public suit.',
    gamesIntro: 'Lancez une roue, une grille mystère ou un tournoi, puis partagez une page spectateur pour que votre public suive le jeu.',
    previewLabel: 'ILLUSTRATION INTERACTIVE',
    previewNote: 'Une démonstration simplifiée des formats de jeu. Ce n’est ni l’application ni une diffusion en direct.',
    games: [
      { id: 'wheel', name: 'Roue', body: 'Ajoutez un tour de roue au direct. Les spectateurs suivent la roue dans la vue partagée pendant que vous l’animez.' },
      { id: 'grid', name: 'Grille mystère', body: 'Faites de la révélation un moment du direct. Vous révélez une case; le public voit le résultat sur la page partagée.' },
      { id: 'bracket', name: 'Tournoi', body: 'Créez un face-à-face. Vous lancez les duels aux dés pendant que le public suit le tableau du tournoi.' },
    ],
    previewPrompt: 'Essayez un format ci-dessous.',
    spin: 'Faire tourner la roue démo',
    spinResult: 'Sélection démo :',
    spinning: 'La roue tourne…',
    reveal: 'Révéler la case',
    revealed: 'Case {n} révélée',
    gridPrompt: 'Choisissez une case à révéler.',
    bracketAction: 'Lancer le prochain duel',
    bracketPrompt: 'Jouez les deux demi-finales, puis la finale.',
    matchResult: 'Duel {n} : {winner} avance',
    duelLabel: 'Exemple de duel aux dés',
    dieResult: 'Résultat du dé de démonstration',
    bracketResult: 'Gagnant démo :',
    reset: 'Réinitialiser l’aperçu',
    bracketLabel: 'Illustration d’un tournoi à quatre participants',
    shareTitle: 'Un lien pour le public.',
    shareSteps: [
      { title: 'Lancez une session', body: 'Ouvrez le partage spectateur depuis votre jeu.' },
      { title: 'Partagez la vue', body: 'Copiez le lien spectateur ou affichez son code QR.' },
      { title: 'Gardez les commandes', body: 'Le public regarde seulement. Vous gérez le jeu et terminez la session.' },
    ],
    plansKicker: 'POUR BIEN CHOISIR',
    plansTitle: 'Les bases pour commencer. Pro pour aller plus loin.',
    free: 'Gratuit', freeIntro: 'Pour organiser votre inventaire et utiliser les outils de prix de base.',
    freeItems: ['Configuration de l’inventaire', 'Outils de tarification de base'],
    pro: 'Pro', proIntro: 'Pour calculer un prix selon votre profit cible et approfondir le suivi des ventes.',
    proItems: ['Calcul du prix selon le profit cible', 'Suivi des ventes', 'Rapports de portefeuille', 'Mode expert'],
    pricingNote: 'Consultez les prix Pro et les détails des formules dans l’application.',
    signIn: 'Une connexion Google est nécessaire pour utiliser l’application.',
    plansCta: 'Voir les formules dans l’application',
  },
}
